name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-ecr-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 307946679963.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
      run: |
        docker build -t kidney .
        docker tag kidney:latest 307946679963.dkr.ecr.eu-north-1.amazonaws.com/kidney:latest

      - name: Push Docker image to ECR
        run: |
          docker push 307946679963.dkr.ecr.eu-north-1.amazonaws.com/kidney:latest
          
          
  Continuous-Deployment:
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 307946679963.dkr.ecr.eu-north-1.amazonaws.com
      
      
      - name: Deploy to EC2
        env:
          IMAGE_URI: 307946679963.dkr.ecr.eu-north-1.amazonaws.com/kidney:latest
        run: |
          # Connect to EC2 and pull the Docker image
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_KEY_PAIR_PATH }}" ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo docker pull $IMAGE_URI
            sudo docker stop $(sudo docker ps -a -q) || true
            sudo docker run -d -p 80:80 $IMAGE_URI
          EOF
